# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ci

on:
  push:
    branches: [ "master", "release/**" ]
  pull_request:
    branches: [ "master", "release/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - uses: dotnet/nbgv@v0.4.2
      name: NBGV
      id: nbgv
      with:
        setAllVars: "true"

    - name: Build Packages
      run: dotnet build src/Uno.DebugRainbows/Uno.DebugRainbows.csproj
