# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ci

on:
  push:
    branches: [ "master", "release/**" ]
  pull_request:
    branches: [ "master", "release/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - uses: dotnet/nbgv@v0.4.2
      name: NBGV
      id: nbgv
      with:
        setAllVars: "true"
    - name: Generate Informational Version
      id: NBGV_InformationalVersion
      shell: pwsh
      run: |
        $InformationalVersion="${{ steps.nbgv.outputs.SemVer2 }}+${{ steps.nbgv.outputs.BuildingRef }}".Replace("refs/heads/","").Replace("/","-")
        echo "Informational Version: $InformationalVersion"
        echo "NBGV_InformationalVersion=$InformationalVersion" >> $GITHUB_ENV
    - name: Build Packages
      run: |
        $adjustedPackageVersion="${{ steps.nbgv.outputs.SemVer2 }}".ToLower();
        dotnet build src/Uno.DebugRainbows/Uno.DebugRainbows.csproj -c Release -p:PackageVersion=$adjustedPackageVersion -p:Version=${{ steps.nbgv.outputs.SimpleVersion }} /bl:./artifacts/debugrainbows-pack.binlog -o ./artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts